### ISSUE TITLE
滚动通知栏

### ISSUE THREAD

**Issue by sqdengdeng** [sqdengdeng/blog#50]
# 滚动通知栏

### HTML：
```html
<div class="box">
  <p>
    重要通知：经网易大学研究决定将于本月月底举行秋季运动会，具体比赛项目另行通知，望各位老师及同学高度重视，积极参与，各班报名截止日期为9月10日。
    重要通知：经网易大学研究决定将于本月月底举行秋季运动会，具体比赛项目另行通知，望各位老师及同学高度重视，积极参与，各班报名截止日期为9月10日。
  </p>
</div>
```
### CSS：
```css
.box {
  width: 100%;
  background: #fff;
  position: relative;
}
p {
  overflow: hidden;
  white-space: nowrap;
  height: 30px;
  line-height: 30px;
  position: absolute;
  top: 5px;
  left: 0;
}
```
### JS
```js
const notice = document.querySelector('p')
const iSpeed = 4
const timer = setInterval(function(){
  notice.style.left=`${notice.offsetLeft-iSpeed}px`
  if(notice.offsetLeft <= -notice.offsetWidth/2){
      notice.style.left='0px';
  }
},60);
```
