### ISSUE TITLE
iframe 兼容 iOS 低版本

### ISSUE THREAD

**Issue by sqdengdeng** [sqdengdeng/blog#57]
在iOS11.2和iOS12.1 上面，iframe设置height是不生效的，问题就是，在一个固定高度的盒子里，滚动不了。自己手机是13.4，就是ok的。
解决方案就是，外层套一个div，父元素的高度是写死的，不能弹性铺满，iframe的宽度和高度都是100%
```css
.olympic-body {
  box-sizing: border-box;
  max-width: 100%;
  max-height: 100%;
  height: 460px;
  width: 100%;

  iframe {
    border: none;
    width: 100%;
    height: 100%;
  }
  .olympic-body-container,
  .olympic-body-container iframe {
    width: 100%;
    height: 100%;

    margin: 0 !important;
    padding: 0 !important;
    box-sizing: border-box;
  }
  .scroll {
    overflow-y: scroll !important;
    -webkit-overflow-scrolling: touch !important;
  }
}
```

```js
<div className="olympic-body">
    <div className="olympic-body-container scroll">
         <iframe src={item.url} />
    </div>
</div>
```
参考：https://stackoverflow.com/questions/49749442/workaround-to-ios-11-webkit-iframe-bugs
